# Site
url: https://vikpe.org/github-pages-starter
name: GitHub Pages starter

# Custom settings (GitHub Pages Starter)
custom_settings:
  # required
  is_development: false

  # optional/convenience
  description: Fast builds, live reload, GitHub Pages ready.

# Handling / Reading
destination: ./../public
safe: true
ignore_theme_config: true
strict_front_matter: true
include:
  - _pages

keep_files:
  - assets # generate by gulp, not jekyll

exclude:
  - _data/rev-manifest.json
  - .gitignore
  - CNAME
  - Gemfile
  - Gemfile.lock

# Conversion
markdown: kramdown
incremental: false

# Output
timezone: Europe/Stockholm

# Markdown Processors
kramdown:
  input: GFM
  hard_wrap: false
